### ISSUE TITLE
"date: invalid date" in git-rev.sh

### ISSUE THREAD

**Issue by anatolym** [umputun/baseimage#1]
If commit author username contains more than one word with whitespace separator the command bellow returns an error:

https://github.com/umputun/baseimage/blob/9b583a7a95007508ba06b919b25b21e14f983ee1/build.go/git-rev.sh#L21
returns `date: invalid date '@<anatoly.milko@gmail.com>'` for input
```bash
$ echo $log
8cd2627888a5808bf1c843223d35bf2d33ca7b46 9285135db8f825adb61d1b1904ed848afa0955d1 Anatoly Milkov <anatoly.milko@gmail.com> 1529209104 -0500 commit: remove bytes slices, use io.TeeReader #78
```

Not critical, but can return incorrect `version` and generate following output on `docker-compose build`:
```
Step 22/41 : RUN     version=$(/script/git-rev.sh) &&     echo "version $version" &&     go build -o remark -ldflags "-X main.revision=${version} -s -w" ./app
 ---> Running in 6c863cab384f
date: invalid date '@<anatoly.milko@gmail.com>'
version avatar-store-resize-8cd2627-
Removing intermediate container 6c863cab384f
 ---> a8e5a3a8fd37
```

**Comment by umputun** [comment]
the way this file formatted makes reliable parsing hard. The best I can think about is to detect email by leading `<` for the single part name as well as two-part name.

**Comment by anatolym** [comment]
Oh, I haven't noticed you fixed this already and implemented with regexp. 
Just in case it could look like this
```bash
# get time stamp
log=$(tail -n1 .git/logs/$ref)
[[ $log =~ \<.+\>[[:space:]]([0-9]+)[[:space:]] ]]
ts=$(date -d "@${BASH_REMATCH[1]}" +'%Y%m%dT%H:%M:%S')
```

**Comment by umputun** [comment]
`/scripts/version.sh` is a modern replacement for git-rev.sh (left for back-compat only) and it doesn't do a "manual" parsing anymore however expects a presence of proper `.git` in case if running outside of ci (actions)
