### ISSUE TITLE
Add arg timezone

### ISSUE THREAD

**Issue by zorion79** [umputun/baseimage#15]
Please, add arg or env timezone.

https://github.com/umputun/baseimage/blob/9c0adc77ff7e8549fd25e4a4a388719d5235f190/build.go/Dockerfile#L15

**Comment by umputun** [comment]
added as `TIME_ZONE` env, the same as for `base.alpine`. Pls take a look and let me know if it fixed your issue.

**Comment by zorion79** [comment]
I can't run `docker build` with ENV.
When i used this before fix with docker-compose, base.alpine working fine.

```Dockerfile
# This part not working now. 
# Maybe this will be working if i will pull this image first time from docker hub with docker-compose?
FROM umputun/baseimage:buildgo-latest as build-backend

ENV TIME_ZONE=$TIME_ZONE

RUN \
    echo $TIME_ZONE && \
    date

#This working fine with docker-compose .env file. Maybe i'm pulled this first time with docker-compose?
FROM umputun/baseimage:app-latest

ENV TIME_ZONE=$TIME_ZONE

WORKDIR /srv

COPY --from=build-backend /build/prog /srv/prog```

**Comment by umputun** [comment]
A few things are going on here:

1. Where was a bug (missing copy zoneinfo to localtime), should be resolved
2.  All the changes are not tagged (released) yet, so the image is not `umputun/baseimage:buildgo-latest` but `umputun/baseimage:buildgo`
3. I don't really understand how you planned to use it. TIME_ZONE is not run-time, but a build-time parameter here. Unlike `baseimage:app` which runs the actual app, the  `baseimage:buildgo` doesn't have any run-time init and has no place to set it. I also not sure how you expected it to work. And if you need to set a custom timezone as a part of your build-backend just set it to whatever you need as a part of your docker file.
4. I thought your goal was to make your own baseimage and pass TIME_ZONE at build time

**Comment by zorion79** [comment]
1. Yes.
2. I tested this with docker-compose, but this is not help. I didn't understand why this work with your base.alpine in my Dockerfile.
3. I used this with revision name from git time. My last commit time was `Date:   Thu Feb 25 11:34:45 2021 +1000` Program name `branch-name-59ef653-20210224T19:34:45` This is not beautiful. Как вы говорите - страдает чувство прекрасного.
4. I don't want to make my image. I can do this and i did it before but why? This image perfect as is.

I think. This issue can be closed. I'll will reflect about this. Maybe I'll find solution.

Thank you!

**Comment by umputun** [comment]
>  I didn't understand why this work with your base.alpine in my Dockerfile.

This is a very different use-case because of base.alpine actually runs, but buildgo just a base image for a build stage

As I mentioned, the solution is just to set time zone directly in your dockerfile

**Comment by zorion79** [comment]
2. I catch it. It was the script `init.sh`
