### ISSUE TITLE
Run CMD under app user

### ISSUE THREAD

**Issue by andrexus** [umputun/baseimage#2]
Documentation says that **(provided) CMD runs under app user (uid=1001)** but the last line in the init.sh script just runs the provided command without switching the user before:
```
echo "execute $@"
$@
```
Probably this line should be changed to something like that:
```
echo "execute $@"
/sbin/su-exec app $@
```

But on the other hand it will make this script unusable in case the derived Dockerfile adds command
```
USER app
```
because in this case every process will be running under user app and su-exec will fail

**Comment by umputun** [comment]
yeah, I figured enforcing `app` user is too restrictive but never corrected readme. Fixed
