### ISSUE TITLE
dumb-init vs docker run --init

### ISSUE THREAD

**Issue by zonescape** [umputun/baseimage#3]
Umputun, why does baseimage need dumb-init if one can use an init process provided by docker itself?
[Specify an init process](https://docs.docker.com/engine/reference/run/#specify-an-init-process)
```
$ docker container run -it --init --rm alpine sh
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 /dev/init -- sh
    8 root      0:00 sh
   11 root      0:00 ps
```

**Comment by umputun** [comment]
Good point. This image was made a while ago and back in days, docker didn't have internal `tini`.  Probably it can be dropped for modern dockers.
