### ISSUE TITLE
Outdated docker tags

### ISSUE THREAD

**Issue by paskal** [umputun/baseimage#4]
[Baseimage tags page](https://hub.docker.com/r/umputun/baseimage/tags) shows that only `app` and `buildgo` tags are updated, however there are also `app-latest` and `buildgo-latest` images which were not updated after latest commit.

**Comment by umputun** [comment]
this was an intentional change. `*-latest` will be updated only on release (tag). At the same time, it will make `:app-{tag}` and `:buildgo-{tag}` images
