### ISSUE TITLE
[baseimage:buildgo] go mod vendor support

### ISSUE THREAD

**Issue by paskal** [umputun/baseimage#6]
Hello Eugene, thank you for the amazing work on this project!
Recently I've switched a project which use buildgo image to `go mod` with `go mod vendor` and found out that [coverage.sh](/umputun/baseimage/blob/master/build.go/coverage.sh) and [checkvendor.sh](/umputun/baseimage/blob/master/build.go/checkvendor.sh) don't support new vendoring scheme.

I don't know what should be going in checkvendor.sh with the new paradigm but coverage.sh should allow passing an argument which will enable `-mod=vendor` option for `go test` command, and it will work fine. Now it works as well but fetches all packages on each run.

**Comment by umputun** [comment]
I think setting `ENV GOFLAGS="-mod=vendor"` as a part of build stage should resolve it without modifying coverage.sh 

Regarding checkvendor.sh - yeah, this script is for pre-mod packaging and for a particular tool (govendor) only. However, this script not even needed for mod. If you have `GOFLAGS="-mod=vendor"` set, `go get` will be rejected with "go get: disabled by -mod=vendor", and build will fail.

**Comment by paskal** [comment]
Thanks! `GOFLAGS="-mod=vendor"` works fine.
